#!/bin/sh

set -x
set -e # Exit on first error

ROOTDIR="$1"

export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
export LC_ALL=C LANGUAGE=C LANG=C

# Install non-free binary blob and kernel needed to boot Raspberry Pi
wget https://raw.github.com/Hexxeh/rpi-update/master/rpi-update \
    -O ${ROOTDIR}/usr/local/sbin/rpi-update
chmod a+x ${ROOTDIR}/usr/local/sbin/rpi-update
mkdir -p ${ROOTDIR}/lib/modules
touch ${ROOTDIR}/boot/start.elf
# Do not try to update itself, avoid making backups, skip warnings
export UPDATE_SELF=0 SKIP_BACKUP=1 SKIP_WARNING=1
chroot ${ROOTDIR} rpi-update

# Add module for hardware RNG
cat <<EOF >> ${ROOTDIR}/etc/modules
bcm2708_rng
EOF

# Add an apt repository with apt preferences
set_apt_sources() {
    SUITE="$1"
    PIN_PRIORITY="$2"
    COMPONENTS="main"
    cat <<EOF >> ${ROOTDIR}/etc/apt/sources.list
# Repository: $SUITE
deb $APT_MIRROR $SUITE $COMPONENTS
EOF
    if [ -n "$PIN_PRIORITY" ]
      then
        cat <<EOF > ${ROOTDIR}/etc/apt/preferences.d/${SUITE}.pref
Package: *
Pin: release n=$SUITE
Pin-Priority: $PIN_PRIORITY
EOF
    fi
}

echo "Add Debian ${DEB_RELEASE}-backports repository"
set_apt_sources ${DEB_RELEASE}-backports
echo "Add Debian stretch repository"
set_apt_sources stretch 100

# Create ooniprobe log directory
mkdir -p ${ROOTDIR}/var/log/ooni/

# Copy required scripts, cronjobs and config files to lepidopter
# Rsync Directory/file hieratchy to image
rsync -avp lepidopter-fh/ ${ROOTDIR}/

# Install ooniprobe via setup script
chroot ${ROOTDIR} /setup-ooniprobe.sh
rm ${ROOTDIR}/setup-ooniprobe.sh

# Remove SSH host keys and add regenerate_ssh_host_keys SYSV script
chroot ${ROOTDIR} /remove_ssh_host_keys.sh
rm ${ROOTDIR}/remove_ssh_host_keys.sh

echo "Customize script finished successfully."
exit 0
