OONI_CONFIG="/etc/ooniprobe/ooniprobe.conf"
OONI_HOME="/opt/ooni"
OONI_REPORTS="/opt/ooni/reports"
OONI_DECK_CONFIG="/etc/ooniprobe/oonideckconfig"
OONI_CRONJOBS_LOG="/var/log/ooni/cronjobs.log"
OONIREPORT_LOG="/var/log/ooni/oonireport.log"
