#!/bin/bash

. /etc/default/lepidopter

IMAGE_DOC_URL="https://github.com/TheTorProject/lepidopter/blob/master/README.md"
IMAGE_SOURCE_URL="https://github.com/TheTorProject/lepidopter"
KERNEL_VERSION=$(uname -r)

[ -r /etc/lsb-release ] && . /etc/lsb-release
if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
        # Fall back to using the very slow lsb_release utility
        DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

date=$(date)
load=$(cat /proc/loadavg | awk '{print $1}')
root_usage=$(df -h / | awk '/\// {print $(NF-2)}')
memory_usage=$(free -m | awk '/Mem:/ { total=$2 } /buffers\/cache/ { used=$3 } \
                END { printf("%3.1f%%", used/total*100)}')
users=$(users | wc -w)
time=$(uptime | grep -ohe 'up .*' | sed 's/,/\ hours/g' |
        awk '{ printf $2" "$3 }')
processes=$(ps aux | wc -l)
ip=$(ifconfig $(route | grep default | awk '{ print $8 }') | grep "inet addr" |
                awk -F: '{print $2}' | awk '{print $1}')

[ -f /etc/motd.head ] && cat /etc/motd.head || true
printf "\n"
printf "Welcome on %s (%s %s %s %s)\n" "$(hostname)" "${DISTRIB_DESCRIPTION}" \
       "$(uname -o)" "${KERNEL_VERSION}" "$(uname -m)"
printf "\n"
printf "System information as of: %s\n" "$date"
#printf "\n"
printf "Memory usage:\t%s\t\tInt IP Address:\t%s\n" "$memory_usage" "$ip"
printf "System load:\t%s\t\tSystem uptime:\t%s\n" "$load" "$time"
printf "Avail Space:\t%s\t\tImage build:\t%s\n" "$root_usage" "$LEPIDOPTER_BUILD"
printf "Local Users:\t%s\t\tProcesses:\t%s\n" $users $processes
printf "\n"
printf "Documentation:\t%s\n" "$IMAGE_DOC_URL"
printf "Image source:\t%s\n" "$IMAGE_SOURCE_URL"
printf "\n"
